# Generated by Django 5.2.1 on 2026-02-24 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'フレーバータグ',
                'verbose_name_plural': 'フレーバータグ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='都道府県名')),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='蔵元名')),
                ('Prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breweries', to='sake_app.prefecture', verbose_name='都道府県')),
            ],
            options={
                'verbose_name': '蔵元',
                'verbose_name_plural': '蔵元',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sake',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='銘柄名')),
                ('f1_hanayaka', models.FloatField(blank=True, null=True, verbose_name='華やか')),
                ('f2_houjun', models.FloatField(blank=True, null=True, verbose_name='芳醇')),
                ('f3_juukou', models.FloatField(blank=True, null=True, verbose_name='重厚')),
                ('f4_odayaka', models.FloatField(blank=True, null=True, verbose_name='穏やか')),
                ('f5_dry', models.FloatField(blank=True, null=True, verbose_name='ドライ')),
                ('f6_keikai', models.FloatField(blank=True, null=True, verbose_name='軽快')),
                ('brewery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sakes', to='sake_app.brewery', verbose_name='蔵元')),
                ('flavor_tags', models.ManyToManyField(blank=True, related_name='sakes', to='sake_app.flavortag', verbose_name='フレーバータグ')),
            ],
            options={
                'verbose_name': '日本酒',
                'verbose_name_plural': '日本酒',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=False, verbose_name='いいね')),
                ('is_drunk', models.BooleanField(default=False, verbose_name='飲んだ')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評価')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('drunk_at', models.DateField(blank=True, null=True, verbose_name='飲んだ日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sake_app.sake', verbose_name='日本酒')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sake_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '日本酒ログ',
                'verbose_name_plural': '日本酒ログ',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'sake'), name='unique_user_sake_log')],
            },
        ),
    ]
