# Generated by Django 5.2.1 on 2026-02-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sake_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sake',
            name='flavor_tags',
        ),
        migrations.DeleteModel(
            name='FlavorTag',
        ),
    ]
