# Generated by Django 5.2.1 on 2026-02-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sake_app', '0002_remove_sake_flavor_tags_delete_flavortag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'ordering': ['id'], 'verbose_name': '蔵元', 'verbose_name_plural': '蔵元'},
        ),
        migrations.AlterModelOptions(
            name='sake',
            options={'ordering': ['id'], 'verbose_name': '日本酒', 'verbose_name_plural': '日本酒'},
        ),
    ]
