# Generated by Django 5.2.1 on 2026-02-25 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sake_app', '0003_alter_brewery_options_alter_sake_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewery',
            old_name='Prefecture',
            new_name='prefecture',
        ),
    ]
